return {
  "mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "hyprls",
      "json-lsp",
      "lua-language-server",
      "luaformatter",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "pyright",
      "ruff",
      "shellcheck",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "tree-sitter-cli",
      "vtsls",
      -- "harper-ls",
    },
  },
}
